colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

[homepage]
  layout = "profile"
  homepageImage = "img/williamicon.png"
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = true
  cardViewScreenWidth = false

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = false
  showBreadcrumbs = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  sharingLinks = ["linkedin", "twitter", "reddit", "email"]
  showZenMode = true
  showRelatedContent = true
  relatedContentLimit = 3
  showEdit = true
  editURL = "https://github.com/wshayes/wshayes.github.io/edit/main/content/"

[list]
  showBreadcrumbs = true
  showTableOfContents = false
  groupByYear = true
  cardView = true

[taxonomy]
  showTermCount = true
  showBreadcrumbs = true
  cardView = true

[term]
  showBreadcrumbs = true
  groupByYear = true
  cardView = true
